server:
  port: 8082

spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/,http://127.0.0.1:8081/eureka/
