server:
  port: 8082
  servlet:
    context-path: /service

spring:
  application:
    name: service-provider

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.100.101:8080/eureka/,http://192.168.100.102:8080/eureka/
