spring:
  datasource:
    url: jdbc:mysql://192.168.200.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: dev
    password: dev
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-total: 20
      max-wait-millis: 3000
      initial-size: 10
    driver-class-name: com.mysql.jdbc.Driver


