server:
  port: 9000
  servlet:
    context-path: /test
spring:
  datasource:
    url: jdbc:mysql://192.168.100.1:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: test
    password: test
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-total: 20
      max-wait-millis: 3000
      initial-size: 10
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    tiger.dao: debug
    org.springframework: warn
mybatis:
  configuration:
    map-underscore-to-camel-case: true
