server:
  port: 8081

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
spring:
  application:
    name: eureka-server
logging:
  config: ./config/log4j2.xml
