server:
  port: 8080
  servlet:
    context-path: /config

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/E:/data/config-repo/
  profiles:
    active: native
  application:
    name: config-server

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.100.101:8080/eureka/,http://192.168.100.102:8080/eureka/