server:
  port: 9000
  servlet:
    context-path: /test
    session:
      timeout: 60s
spring:
  datasource:
    url: jdbc:mysql://192.168.100.1:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: test
    password: test
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-total: 20
      max-wait-millis: 3000
      initial-size: 10
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: 3000ms
        max-idle: 4
        min-idle: 2
    host: 192.168.100.101
    port: 6379
    password: dev
  session:
    store-type: redis
logging:
  level:
    tiger.dao: debug
    org.springframework: warn
mybatis:
  configuration:
    map-underscore-to-camel-case: true
